config/routes.rb
require "constraints/subdomain_required"

Rails.application.routes.draw do


  devise_for :users
  
  constraints(SubdomainRequired) do
     scope module: "accounts" do
     root to: "todos#index", as: :account_root
     resources :invitations, only: [:new, :create]
    end
    resources :todos
  end
  
  get 'pages/home'

  get 'pages/profile'

  get 'pages/explore'
  
  root to: "home#index"
  get "/accounts/new", to: "accounts#new", as: :new_account
  post "/accounts", to: "accounts#create", as: :accounts
  get "signed_out", :to => "users#signed_out"
  
  
end

app/models/account.rb
class Account < ActiveRecord::Base
    
    validates :subdomain, presence: true, uniqueness: true
    
    belongs_to :owner, class_name: "User"
    accepts_nested_attributes_for :owner
end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts/base_controller.rb
module Accounts
 class BaseController < ApplicationController
       #before_action :authenticate_user!
       skip_before_action :authenticate_user!
       
         def current_account
         @current_account ||= Account.find_by!(subdomain: request.subdomain)
         end
         helper_method :current_account
        
         def owner?
         current_account.owner == current_user
         end
         helper_method :owner?
        
 end
end

app/controllers/accounts/invitations_controller.rb
class Accounts::InvitationsController < ApplicationController
end

app/controllers/accounts/pages_controller.rb
module Accounts

  class PagesController < Accounts::BaseController
    def home
    end
  
    def profile
    end
  
    def explore
    end
  end
end

app/controllers/accounts/todos_controller.rb
module Accounts
  
  class TodosController < Accounts::BaseController
    
    before_action :set_todo, only: [:show, :edit, :update, :destroy]
  
    # GET /todos
    # GET /todos.json
    def index
      @todos = Todo.all
    end
  
    # GET /todos/1
    # GET /todos/1.json
    def show
    end
  
    # GET /todos/new
    def new
      @todo = Todo.new
    end
  
    # GET /todos/1/edit
    def edit
    end
  
    # POST /todos
    # POST /todos.json
    def create
      @todo = Todo.new(todo_params)
  
      respond_to do |format|
        if @todo.save
          format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
          format.json { render :show, status: :created, location: @todo }
        else
          format.html { render :new }
          format.json { render json: @todo.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /todos/1
    # PATCH/PUT /todos/1.json
    def update
      respond_to do |format|
        if @todo.update(todo_params)
          format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
          format.json { render :show, status: :ok, location: @todo }
        else
          format.html { render :edit }
          format.json { render json: @todo.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /todos/1
    # DELETE /todos/1.json
    def destroy
      @todo.destroy
      respond_to do |format|
        format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_todo
        @todo = Todo.find(params[:id])
      end
  
      # Never trust parameters from the scary internet, only allow the white list through.
      def todo_params
        params.require(:todo).permit(:title, :notes)
      end
  end
 
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
    def new
        @account = Account.new
        @account.build_owner
    end
    
    def create
        @account = Account.new(account_params)
        if @account.save
            sign_in(@account.owner)
            flash[:notice] = "Your account has been successfully created."
            redirect_to root_url(subdomain: @account.subdomain)
        else
            flash.now[:alert] = "Sorry, your account could not be created."
            render :new
        end
    end
    
    private
    def account_params
        params.require(:account).permit(:name, :subdomain,{ owner_attributes: [
        :username, :email, :password, :password_confirmation
        ]}
        )
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/accounts/new.html.erb
<div class='row'>
  <div class='col-md-offset-4 col-md-4 content'>
   <h2>Create a new account</h2>

        <%= simple_form_for(@account) do |account| %>
        <%= account.input :name %>
        <%= account.input :subdomain %>
        
        <%= account.fields_for :owner do |owner| %>
        <%= owner.input :username %>
        <%= owner.input :email %>
        <%= owner.input :password %>
        <%= owner.input :password_confirmation %>
        <% end %>
         
        <%= account.submit class: "btn btn-primary" %>
        <% end %>
</div>
</div>

app/views/accounts/todos/_form.html.erb
<%= form_for(@todo, html: {class: 'form-horizontal'}) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field form-group">
    <%= f.label :title, class: 'col-sm-2 control-label' %><br>
    <div class="col-sm-10">
         <%= f.text_field :title, class: 'form-control' %>
    </div>
</div>
  <div class="field form-group">
    <%= f.label :notes, class: 'col-sm-2 control-label' %><br>
     <div class="col-sm-10">
         <%= f.text_area :notes, class: 'form-control' %>
     </div>
  </div>
  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
       <%= f.submit %>
      
    </div>
  </div>
<% end %>

app/views/accounts/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
 <%= link_to 'Back', todos_path %>

app/views/accounts/todos/index.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><%= link_to 'View list', todos_path %></li>
  <li><%= link_to 'New todo', new_todo_path %></li>
</ul>
<p id="notice"><%= notice %></p>

<h1>Listing Todos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.title %></td>
        <td><%= todo.notes %></td>
        <td><%= link_to 'Show', todo, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo),  class: "btn btn-info btn-xs" %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, class: 'btn btn-danger btn-xs', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_todo_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"></i> New Todo
<% end %>

app/views/accounts/todos/new.html.erb
 
<ul class="nav nav-tabs" role="tablist">
  <li><%= link_to 'View list', todos_path %></li>
  <li class="active"><%= link_to 'New todo', new_todo_path %></li>
</ul>

<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/accounts/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @todo.notes %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
 <%= link_to 'Back', todos_path %>

app/views/home/index.html.erb
<div class='content col-md-8'>
   <%= link_to "Create a new account", new_account_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'shared/navigation' %>
 <div id="main-container" class="container">

   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
      <div class="row">
        <div class="col-xs-3">
          <h3>Tealeaf Academy Todo</h3>
        </div>
        <div class="col-xs-9">
          <%= yield %>
        </div>
      </div>
 </div>

</body>
</html>

app/views/pages/explore.html.erb
<h1>Pages#explore</h1>
<p>Find me in app/views/pages/explore.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/profile.html.erb
<h1>Pages#profile</h1>
<p>Find me in app/views/pages/profile.html.erb</p>
<% if owner? %>
<li><%= link_to "Invite User", new_invitation_path %></li>
<% end %>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Tealeaf Todo</a>
      
      
      <ul class="nav navbar-nav">
        
         <% if user_signed_in? %>
            <li><%= link_to('Log Out', destroy_user_session_path, :method => :delete) %></li>
           
         <% else %>
            <li><%= link_to('Sign In', new_user_session_path) %></li>
         <% end %>
     </ul>
         
    </div>
  </div>
</nav>